services:
    client:
        container_name: client
        build:
            context: ./
            dockerfile: Dockerfile.dev
            # We use args to set build time variable
            args:
                VITE_API_URL: ${VITE_API_URL}
        
        restart: unless-stopped
        expose:
            - ${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
        env_file: ".env"
        command: yarn dev
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules