/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonIndexImport } from './routes/person.index'
import { Route as PersonIdImport } from './routes/person.$id'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const LoginLazyImport = createFileRoute('/login')()
const GamerLazyImport = createFileRoute('/gamer')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const GamerLazyRoute = GamerLazyImport.update({
  id: '/gamer',
  path: '/gamer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/gamer.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PersonIndexRoute = PersonIndexImport.update({
  id: '/person/',
  path: '/person/',
  getParentRoute: () => rootRoute,
} as any)

const PersonIdRoute = PersonIdImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/gamer': {
      id: '/gamer'
      path: '/gamer'
      fullPath: '/gamer'
      preLoaderRoute: typeof GamerLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
    '/person/$id': {
      id: '/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof PersonIdImport
      parentRoute: typeof rootRoute
    }
    '/person/': {
      id: '/person/'
      path: '/person'
      fullPath: '/person'
      preLoaderRoute: typeof PersonIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/gamer': typeof GamerLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/person/$id': typeof PersonIdRoute
  '/person': typeof PersonIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/gamer': typeof GamerLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/person/$id': typeof PersonIdRoute
  '/person': typeof PersonIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/gamer': typeof GamerLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/person/$id': typeof PersonIdRoute
  '/person/': typeof PersonIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gamer' | '/login' | '/signup' | '/person/$id' | '/person'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gamer' | '/login' | '/signup' | '/person/$id' | '/person'
  id:
    | '__root__'
    | '/'
    | '/gamer'
    | '/login'
    | '/signup'
    | '/person/$id'
    | '/person/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  GamerLazyRoute: typeof GamerLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  PersonIdRoute: typeof PersonIdRoute
  PersonIndexRoute: typeof PersonIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  GamerLazyRoute: GamerLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  PersonIdRoute: PersonIdRoute,
  PersonIndexRoute: PersonIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/gamer",
        "/login",
        "/signup",
        "/person/$id",
        "/person/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/gamer": {
      "filePath": "gamer.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/signup": {
      "filePath": "signup.lazy.tsx"
    },
    "/person/$id": {
      "filePath": "person.$id.tsx"
    },
    "/person/": {
      "filePath": "person.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
